[project]
name = 'Decentralized-Parking-Management-System'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.reservation]
path = 'contracts/reservation.clar'
clarity_version = 2
epoch = 2.5

[contracts.space-registration]
path = 'contracts/space-registration.clar'
clarity_version = 2
epoch = 2.5

[contracts.violation-reporting]
path = 'contracts/violation-reporting.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
